### PR TITLE
fix: ensure attribute is string

### PR DESCRIPTION
**Pull request by cossssmin**
This fixes a regression introduced in 8601df6

In order to not automatically add `=""` to no-value attributes, the attribute's value is set to `true` if it's empty/undefined.

This can result in a `TypeError: attrStr.split is not a function` because we're using `.spli()` on a `Boolean`.

This PR ensures the value is correct by casting it to a `String`.

### CODE REVIEW

**Review by maltsev — APPROVED** [review]
👍

**Comment by maltsev** [comment]
@cossssmin thanks! I think you can release the npm package yourself (since I have added you as a npm collaborator)?

**Comment by cossssmin** [comment]
Released `1.0.1`, thanks!
